---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oldman-operator-cluster-role
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      # The cluster operator needs to access and manage leases for leader election
      # The "create" verb cannot be used with "resourceNames"
      - leases
    verbs:
      - create

  - apiGroups:
      - coordination.k8s.io
    resources:
      # The cluster operator needs to access and manage leases for leader election
      - leases
    verbs:
      - get
      - list
      - watch
      - delete
      - patch
      - update

  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list

  - apiGroups:
      - oldman.k8soperators.github.com
    resources:
      - operatorobjectmodels
      - operatorobjectmodels/status
      - operatorobjectmodels/finalizers
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - create
      - delete

  - apiGroups:
      - operators.coreos.com
    resources:
      - catalogsources
      - clusterserviceversions
      - operatorgroups
      - subscriptions
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
      - namespaces
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oldman-operator-cluster-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: oldman-operator-cluster-role
subjects:
  - kind: ServiceAccount
    name: oldman-operator
